apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        lb: test1
    spec:
      containers:
        - name: nginx-test1
          image: antonovichvladimir/nginx-test1
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: test1
                  key: message
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 80
          startupProbe:
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
          readinessProbe:
            initialDelaySeconds: 6
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /health
              port: 80